Strings = {
"NoPresente": "Not present",
"Activo": "Active",
"Alarma": "Alarm",
"NoActivo": "Not active",
"AlarmaReconocida": "Acknowledged alarm",
"SCVAGris": "Imagenes/en/SCV-A-Gris.png",
"SCVBGris": "Imagenes/en/SCV-B-Gris.png",
"SCVAOperativo": "Imagenes/en/SCV-A-Operativo.png",
"SCVBOperativo": "Imagenes/en/SCV-B-Operativo.png",
"SCVAAlarma": "Imagenes/en/SCV-A-Alarma.png",
"SCVBAlarma": "Imagenes/en/SCV-B-Alarma.png",
"SCVAAlarmaDesconocida": "Imagenes/en/SCV-A-AlarmaDesconocida.png",
"SCVBAlarmaDesconocida": "Imagenes/en/SCV-B-AlarmaDesconocida.png",
"SCVCD40Gris": "Imagenes/SCV-CD40-Gris.png",
"SCVCD30Gris": "Imagenes/SCV-CD30-Gris.png",
"SCVCD40Operativo": "Imagenes/SCV-CD40-Operativo.png",
"SCVCD30Operativo": "Imagenes/SCV-CD30-Operativo.png",
"SCVCD40Alarma": "Imagenes/SCV-CD40-Alarma.png",
"SCVCD30Alarma": "Imagenes/SCV-CD30-Alarma.png",
"SCVCD40AlarmaDesconocida": "Imagenes/SCV-CD40-AlarmaDesconocida.png",
"SCVCD30AlarmaDesconocida": "Imagenes/SCV-CD30-AlarmaDesconocida.png",
"PosicionesGris": "Imagenes/en/PosicionesGris.png",
"PosicionesAlarma": "Imagenes/en/PosicionesRojo.png",
"PosicionesOperativo": "Imagenes/en/PosicionesVerde.png",
"PosicionesAlarmaReconocida": "Imagenes/en/PosicionesNaranja.png",
"SCVGris": "Imagenes/en/SCVGrisS.png",
"SCVOperativo": "Imagenes/en/SCVOperativoS.png",
"SCVAlarma": "Imagenes/en/SCVAlarmaS.png",
"SCVAlarmaDesconocida": "Imagenes/en/SCVAlarmaDesconocidaS.png",
"Reserva": "Standby",
"NoOperativo": "Non operating"
};