Strings = {
"NoPresente": "No presente",
"Activo": "Activo",
"Alarma": "Alarma",
"NoActivo": "No activo",
"AlarmaReconocida": "Alarma reconocida",
"SCVAGris": "Imagenes/SCV-A-Gris.png",
"SCVBGris": "Imagenes/SCV-B-Gris.png",
"SCVAOperativo": "Imagenes/SCV-A-Operativo.png",
"SCVBOperativo": "Imagenes/SCV-B-Operativo.png",
"SCVAAlarma": "Imagenes/SCV-A-Alarma.png",
"SCVBAlarma": "Imagenes/SCV-B-Alarma.png",
"SCVAAlarmaDesconocida": "Imagenes/SCV-A-AlarmaDesconocida.png",
"SCVBAlarmaDesconocida": "Imagenes/SCV-B-AlarmaDesconocida.png",
"SCVCD40Gris": "Imagenes/SCV-CD40-Gris.png",
"SCVCD30Gris": "Imagenes/SCV-CD30-Gris.png",
"SCVCD40Operativo": "Imagenes/SCV-CD40-Operativo.png",
"SCVCD30Operativo": "Imagenes/SCV-CD30-Operativo.png",
"SCVCD40Alarma": "Imagenes/SCV-CD40-Alarma.png",
"SCVCD30Alarma": "Imagenes/SCV-CD30-Alarma.png",
"SCVCD40AlarmaDesconocida": "Imagenes/SCV-CD40-AlarmaDesconocida.png",
"SCVCD30AlarmaDesconocida": "Imagenes/SCV-CD30-AlarmaDesconocida.png",
"PosicionesGris": "Imagenes/PosicionesGris.png",
"PosicionesAlarma": "Imagenes/PosicionesRojo.png",
"PosicionesOperativo": "Imagenes/PosicionesVerde.png",
"PosicionesAlarmaReconocida": "Imagenes/PosicionesNaranja.png",
"SCVGris": "Imagenes/SCVGrisS.png",
"SCVOperativo": "Imagenes/SCVOperativoS.png",
"SCVAlarma": "Imagenes/SCVAlarmaS.png",
"SCVAlarmaDesconocida": "Imagenes/SCVAlarmaDesconocidaS.png",
"Reserva": "Reserva",
"NoOperativo": "No operativo"
};