Strings = {
"NoPresente": "Absent",
"Activo": "Actif",
"Alarma": "Alarme",
"NoActivo": "Pas actif",
"AlarmaReconocida": "Alarme reconnue",
"SCVAGris": "Imagenes/fr/SCV-A-Gris.png",
"SCVBGris": "Imagenes/fr/SCV-B-Gris.png",
"SCVAOperativo": "Imagenes/fr/SCV-A-Operativo.png",
"SCVBOperativo": "Imagenes/fr/SCV-B-Operativo.png",
"SCVAAlarma": "Imagenes/fr/SCV-A-Alarma.png",
"SCVBAlarma": "Imagenes/fr/SCV-B-Alarma.png",
"SCVAAlarmaDesconocida": "Imagenes/fr/SCV-A-AlarmaDesconocida.png",
"SCVBAlarmaDesconocida": "Imagenes/fr/SCV-B-AlarmaDesconocida.png",
"SCVCD40Gris": "Imagenes/fr/SCV-CD40-Gris.png",
"SCVCD30Gris": "Imagenes/fr/SCV-CD30-Gris.png",
"SCVCD40Operativo": "Imagenes/fr/SCV-CD40-Operativo.png",
"SCVCD30Operativo": "Imagenes/fr/SCV-CD30-Operativo.png",
"SCVCD40Alarma": "Imagenes/fr/SCV-CD40-Alarma.png",
"SCVCD30Alarma": "Imagenes/fr/SCV-CD30-Alarma.png",
"SCVCD40AlarmaDesconocida": "Imagenes/fr/SCV-CD40-AlarmaDesconocida.png",
"SCVCD30AlarmaDesconocida": "Imagenes/fr/SCV-CD30-AlarmaDesconocida.png",
"PosicionesGris": "Imagenes/fr/PosicionesGris.png",
"PosicionesAlarma": "Imagenes/fr/PosicionesRojo.png",
"PosicionesOperativo": "Imagenes/fr/PosicionesVerde.png",
"PosicionesAlarmaReconocida": "Imagenes/fr/PosicionesNaranja.png",
"SCVGris": "Imagenes/fr/SCVGrisS.png",
"SCVOperativo": "Imagenes/fr/SCVOperativoS.png",
"SCVAlarma": "Imagenes/fr/SCVAlarmaS.png",
"SCVAlarmaDesconocida": "Imagenes/fr/SCVAlarmaDesconocidaS.png",
"Reserva": "Réserve",
"NoOperativo": "Hors service"
};