//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioBackups.ReferenciaEstadisticas {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CD40.es/", ConfigurationName="ReferenciaEstadisticas.EstadisticasSoap")]
    public interface EstadisticasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/RevisarTareasPendientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] RevisarTareasPendientes(string idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/LeeTareas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] LeeTareas(string idSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/CrearTarea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        bool CrearTarea(ServicioBackups.ReferenciaEstadisticas.Tareas t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/EliminarTarea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        bool EliminarTarea(ServicioBackups.ReferenciaEstadisticas.Tareas t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/ListaTareasProgramadas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        string[] ListaTareasProgramadas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/NumeroTotalIndicador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        int NumeroTotalIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/MaximoIndicador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        System.Data.DataSet MaximoIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/MinimoIndicador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        System.Data.DataSet MinimoIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/MediaIndicador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        string MediaIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/DesviacionTipicaIndicador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        string DesviacionTipicaIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/DistribucionPorDiasIndicador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        System.Data.DataSet DistribucionPorDiasIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CD40.es/DistribucionPorHorasIndicador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tablas))]
        System.Data.DataSet DistribucionPorHorasIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CD40.es/")]
    public partial class Tareas : Tablas {
        
        private string idSistemaField;
        
        private string idTareaField;
        
        private string programaField;
        
        private string argumentosField;
        
        private string horaField;
        
        private _Enum_Periodicidad periodicidadField;
        
        private string comentarioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdSistema {
            get {
                return this.idSistemaField;
            }
            set {
                this.idSistemaField = value;
                this.RaisePropertyChanged("IdSistema");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdTarea {
            get {
                return this.idTareaField;
            }
            set {
                this.idTareaField = value;
                this.RaisePropertyChanged("IdTarea");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Programa {
            get {
                return this.programaField;
            }
            set {
                this.programaField = value;
                this.RaisePropertyChanged("Programa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Argumentos {
            get {
                return this.argumentosField;
            }
            set {
                this.argumentosField = value;
                this.RaisePropertyChanged("Argumentos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
                this.RaisePropertyChanged("Hora");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public _Enum_Periodicidad Periodicidad {
            get {
                return this.periodicidadField;
            }
            set {
                this.periodicidadField = value;
                this.RaisePropertyChanged("Periodicidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("Comentario");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CD40.es/")]
    public enum _Enum_Periodicidad {
        
        /// <comentarios/>
        D,
        
        /// <comentarios/>
        M,
        
        /// <comentarios/>
        S,
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Tareas))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CD40.es/")]
    public abstract partial class Tablas : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstadisticasSoapChannel : ServicioBackups.ReferenciaEstadisticas.EstadisticasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstadisticasSoapClient : System.ServiceModel.ClientBase<ServicioBackups.ReferenciaEstadisticas.EstadisticasSoap>, ServicioBackups.ReferenciaEstadisticas.EstadisticasSoap {
        
        public EstadisticasSoapClient() {
        }
        
        public EstadisticasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstadisticasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadisticasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstadisticasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] RevisarTareasPendientes(string idSistema) {
            return base.Channel.RevisarTareasPendientes(idSistema);
        }
        
        public string[] LeeTareas(string idSistema) {
            return base.Channel.LeeTareas(idSistema);
        }
        
        public bool CrearTarea(ServicioBackups.ReferenciaEstadisticas.Tareas t) {
            return base.Channel.CrearTarea(t);
        }
        
        public bool EliminarTarea(ServicioBackups.ReferenciaEstadisticas.Tareas t) {
            return base.Channel.EliminarTarea(t);
        }
        
        public string[] ListaTareasProgramadas() {
            return base.Channel.ListaTareasProgramadas();
        }
        
        public int NumeroTotalIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico) {
            return base.Channel.NumeroTotalIndicador(sistema, familia, indicador, elemento, dia, hasta, elementoFisico);
        }
        
        public System.Data.DataSet MaximoIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico) {
            return base.Channel.MaximoIndicador(sistema, familia, indicador, elemento, dia, hasta, elementoFisico);
        }
        
        public System.Data.DataSet MinimoIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico) {
            return base.Channel.MinimoIndicador(sistema, familia, indicador, elemento, dia, hasta, elementoFisico);
        }
        
        public string MediaIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico) {
            return base.Channel.MediaIndicador(sistema, familia, indicador, elemento, dia, hasta, elementoFisico);
        }
        
        public string DesviacionTipicaIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico) {
            return base.Channel.DesviacionTipicaIndicador(sistema, familia, indicador, elemento, dia, hasta, elementoFisico);
        }
        
        public System.Data.DataSet DistribucionPorDiasIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico) {
            return base.Channel.DistribucionPorDiasIndicador(sistema, familia, indicador, elemento, dia, hasta, elementoFisico);
        }
        
        public System.Data.DataSet DistribucionPorHorasIndicador(string sistema, int familia, int indicador, string elemento, System.DateTime dia, System.DateTime hasta, bool elementoFisico) {
            return base.Channel.DistribucionPorHorasIndicador(sistema, familia, indicador, elemento, dia, hasta, elementoFisico);
        }
    }
}
