//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SectorizacionDll.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SectorizacionDll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ColateralRD {0} (Fr = {1}, Pl = {2}) inválido. Eliminado de la sectorización.
        /// </summary>
        internal static string ColateralRDError {
            get {
                return ResourceManager.GetString("ColateralRDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la sectorización: Prefijo de colateral telefónico inválido ({0}).
        /// </summary>
        internal static string ColateralTlfPrefixError {
            get {
                return ResourceManager.GetString("ColateralTlfPrefixError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sectorización vacía.
        /// </summary>
        internal static string EmptySectError {
            get {
                return ResourceManager.GetString("EmptySectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error obteniendo la configuración activa de la base de datos.
        /// </summary>
        internal static string LoadActiveCfgError {
            get {
                return ResourceManager.GetString("LoadActiveCfgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No todos los sectores reales participan en la sectorización.
        /// </summary>
        internal static string MissingRealSectorError {
            get {
                return ResourceManager.GetString("MissingRealSectorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sectores de distintos núcleos sin agrupar.
        /// </summary>
        internal static string MultiNucleoSectError {
            get {
                return ResourceManager.GetString("MultiNucleoSectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Más de un sector de mantenimiento asociado a la misma UCS.
        /// </summary>
        internal static string MultipleMantSectorError {
            get {
                return ResourceManager.GetString("MultipleMantSectorError", resourceCulture);
            }
        }
    }
}
